Dockerイメージスキャン結果の待機処理をコメントアウトし、スキャン結果の処理を一時的に無効化

diff --git a/.github/workflows/dockerhub2ecr.yaml b/.github/workflows/dockerhub2ecr.yaml
--- a/.github/workflows/dockerhub2ecr.yaml
+++ b/.github/workflows/dockerhub2ecr.yaml
@@ -44,33 +44,33 @@ jobs:
             --repository-name ${{ vars.REPO_NAME_ECR }} \
             --image-id imageTag=${{ vars.IMAGE_TAG_ECR }}
 
-      - name: Wait and check scan results
-        run: |
-          for i in {1..10}; do
-            result=$(aws ecr describe-image-scan-findings \
-              --repository-name ${{ vars.REPO_NAME_ECR }} \
-              --image-id imageTag=${{ vars.IMAGE_TAG_ECR }})
+      # - name: Wait and check scan results
+      #   run: |
+      #     for i in {1..10}; do
+      #       result=$(aws ecr describe-image-scan-findings \
+      #         --repository-name ${{ vars.REPO_NAME_ECR }} \
+      #         --image-id imageTag=${{ vars.IMAGE_TAG_ECR }})
 
-            status=$(echo "$result" | jq -r '.imageScanStatus.status')
-            if [[ "$status" == "COMPLETE" ]]; then
-              echo "Scan complete."
-              echo "$result" > scan-results.json
-              break
-            fi
-            echo "Waiting for scan to complete... ($i)"
-            sleep 10
-          done
+      #       status=$(echo "$result" | jq -r '.imageScanStatus.status')
+      #       if [[ "$status" == "COMPLETE" ]]; then
+      #         echo "Scan complete."
+      #         echo "$result" > scan-results.json
+      #         break
+      #       fi
+      #       echo "Waiting for scan to complete... ($i)"
+      #       sleep 10
+      #     done
 
-          CRITICALS=$(jq '[.imageScanFindings.findings[] | select(.severity == "CRITICAL")] | length' scan-results.json)
-          if [ "$CRITICALS" -gt 0 ]; then
-            echo "Vulnerabilities found: CRITICAL=$CRITICALS"
-            echo "Deleting image..."
-            aws ecr batch-delete-image --repository-name ${{ vars.REPO_NAME_ECR }} \
-              --image-ids imageTag=${{ vars.IMAGE_TAG_ECR }}
-            exit 1
-          else
-            echo "No critical vulnerabilities found."
-          fi
+      #     CRITICALS=$(jq '[.imageScanFindings.findings[] | select(.severity == "CRITICAL")] | length' scan-results.json)
+      #     if [ "$CRITICALS" -gt 0 ]; then
+      #       echo "Vulnerabilities found: CRITICAL=$CRITICALS"
+      #       echo "Deleting image..."
+      #       aws ecr batch-delete-image --repository-name ${{ vars.REPO_NAME_ECR }} \
+      #         --image-ids imageTag=${{ vars.IMAGE_TAG_ECR }}
+      #       exit 1
+      #     else
+      #       echo "No critical vulnerabilities found."
+      #     fi
 
       - name: Upload scan results as artifact
         if: always()
